--- 
abstract: Fallbackable module loader
author: 
  - Gaal Yahas, C<< <gaal at forum2.org> >>
build_requires: 
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Best
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.0
version: 0.12
