---
abstract: 'Fallbackable module loader'
author:
  - 'Gaal Yahas, C<< <gaal at forum2.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Best
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.14
