---
name: Best
version: 0.07
author:
  - 'Gaal Yahas, C<< <gaal at forum2.org> >>'
abstract: Fallbackable module loader
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Best:
    file: lib/Best.pm
    version: 0.07
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
